[package]
name = "gl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = { version = "0.25.0" }
env_logger = { version = "0.11.0" }
glam = "0.25.0"